fixtures:
  forge_modules:
    concat:
      repo: "puppetlabs/concat"
      ref: "6.2.0"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "6.2.0"
    java_ks:
      repo: "puppetlabs/java_ks"
      ref: "3.1.0"
    augeas_core:
      repo: "puppetlabs/augeas_core"
      ref: "1.0.5"
    logrotate: "puppet/logrotate"
    systemd: "camptocamp/systemd"

