---
spec/spec_helper.rb:
  hiera_config: 'spec/fixtures/hiera/hiera.yaml'
Rakefile:
  default_disabled_lint_checks:
    - parameter_documentation
    - parameter_types
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
.travis.yml:
  delete: true
.pdkignore:
  delete: true
.yardopts:
  delete: true
